### ISSUE TITLE
Use Firebase Cloud Storage instead of imagekitio

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/GrowPal#13]
## About

The current implementation uses imagekitio for all image storage. This is not ideal as everytime an image is changed, we have to purge the cache on imagekit's servers. Migrate this to use the firebase cloud storage.

## Resources

This will require me to give you the project's firebase API keys. Aproach the maintainer for the same

## Bounty 100

**Comment by ssether04** [comment]
can i get assigned?

**Comment by anuragrao04** [comment]
@ssether04 go ahead!

**Comment by shreehari2325** [comment]
can i get assigned?

**Comment by shreehari2325** [comment]
@anuragrao04

**Comment by anuragrao04** [comment]
@shreehari2325 go ahead!

**Comment by Advaith2805** [comment]
Can i get assigned

**Comment by rithulkamesh** [comment]
can i get assigned

**Comment by anuragrao04** [comment]
go ahead @rithulkamesh . deassigning @shreehari2325

**Comment by sujay1844** [comment]
Hey @anuragrao04 can you assign me to this? Since @shreehari2325 doesn't seem to be working on it
