### ISSUE TITLE
Move all assets inside organised folders

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/GrowPal#3]
# Explanation
The repository now looks really messy with all the assets just askew in the root folder. We need to move them to their respective folders. One folder for all the `.ui` files, one for the images and other assets.

# Possible way to fix it
- Move all the files to their respective folders.
- Change references IN the .ui files to the images (The .ui files contain references to the images used on that page. When we move the files, this gets affected and it has to be reconfigured in Qt Designer by opening the files one by one)
- Change references in `main.py`

# Resources 
[Qt Documentation](https://doc.qt.io/qtforpython/ )
Revert back to maintainer in case of any doubts :) 

# Time for Open Access: 20 Mins

# Max allowed block time: 1Hr 30Mins

# Bounty Points: 69

**Comment by siddarthpai** [comment]
Hey can i work on this
PES2UG21CS925

**Comment by varuni7** [comment]
Hi can I work on it

**Comment by anuragrao04** [comment]
not assigned to @siddarthpai because he already had another issue at hand. Assigned to @varuni7

**Comment by vrac10** [comment]
Hi can i work on it

**Comment by anuragrao04** [comment]
issue has already been resolved, try sanitising SQL queries!
