### ISSUE TITLE
Make emails better - use HTML Styling

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/GrowPal#4]
# Explanation
We send out emails on the forgot password screen, OTP during registration, and for every purchase. These emails are just plain text and look very bland. We need to use HTML styling to make our emails look better. Feel free to use your creativity! 

# Possible way to fix it
Use HTML attributes to make the email look better. Use bold text, colours, images etc., it is totally up to your creativity :) When you're done, get the HTML code and replace them in the place of the plain text that we have now. As far as I know, this should make the final email display in HTML formatting. Perform good testing before submitting your PR. 

# Maintainers Knowledge
You can use online HTML designers to make our emails. There are drag-and-drop editors available online that are amazing. Explore them! 

# Initial time for open access: 20 Mins

# Maximum allowed block time: 2Hrs

# Bounty Points: 50 to 60 depending on your design

**Comment by gorumeg** [comment]
Hi, can I be assigned to this

**Comment by anuragrao04** [comment]
sure, go ahead

**Comment by tanishkapasarad** [comment]
hey can i be assigned to this?
PES2UG21CS570

**Comment by siddarthpai** [comment]
Hey can i work on this ? PES2UG21CS925

**Comment by anuragrao04** [comment]
this issue is being worked on by @gorumeg . IF and only IF there is no significant progress made on this in 20 mins, I will assign the next person in line.

**Comment by siddarthpai** [comment]
thank you

**Comment by siddarthpai** [comment]
update?

**Comment by anuragrao04** [comment]
@gorumeg has shown significant progress

**Comment by pkmrs** [comment]
Is it still open,if so can I be assigned to this
PES2UG21CS397

**Comment by siddarthpai** [comment]
hey is it still open ?
can i work on it

**Comment by anuragrao04** [comment]
it has been closed, sorry!
