### ISSUE TITLE
Sanitise SQL Queries - Part 1 of 2 - Login pages to Home Page

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/GrowPal#5]
# Explanation
All the SQL Queries used in the project are not sanitised. This makes it highly susceptible to SQL injection attacks. We need to sanitise all queries before they are passed to the database. We do not expect you to sanitise all of the queries since that would take too much time and would be lengthy. Sanitise all queries from the login page to the home page. This includes all the pages that come in between in the flow, including the register page, forgot password, etc.

# Possible Way To Fix It
Use pattern matching/ text parsing specific to the context to sanitise the SQL queries. Another way is to use the sanitisation feature of [SQLAlchemy](https://www.sqlalchemy.org)

# Resources
[SQLAlchemy Sanitisation](https://stackoverflow.com/questions/1997468/sanitizing-user-provided-sql-with-python)

# Bounty Points: 40 to 80 Depending on the number of queries sanitised and the amount of login/code required.  
- You can sanitize a small subset of queries and get lower bounties.[The issue will remain open until majority of sql queries are sanitized.

**Comment by shaurya0148** [comment]
Can i be assigned to this?

**Comment by anuragrao04** [comment]
sure

**Comment by anuragrao04** [comment]
issue is open again

**Comment by anuragrao04** [comment]
being worked on by @varuni7

**Comment by Python-is-better-than-Java** [comment]
Can I be assigned this?

**Comment by Python-is-better-than-Java** [comment]
Ok can I be deassigned?

**Comment by anuragrao04** [comment]
@Python-is-better-than-Java do you want to work on this issue?

**Comment by ProSai8055** [comment]
i would like to work

**Comment by prerana1809** [comment]
Can i work on this issue?

**Comment by ankitam389** [comment]
give me work

**Comment by DedLad** [comment]
can i have it?

**Comment by Python-is-better-than-Java** [comment]
> @Python-is-better-than-Java do you want to work on this issue?

No I would like for someone else to be assigned it

**Comment by anuragrao04** [comment]
@ProSai8055 please go ahead

**Comment by 7Akshu77** [comment]
can i get assigned to this issue
