### ISSUE TITLE
Sanitise SQL Queries - Part 2 of 2- All pages connected to Home Page

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/GrowPal#6]
# Explanation
All the SQL Queries used in the project are not sanitised. This makes it highly susceptible to SQL injection attacks. We need to sanitise all queries before they are passed to the database. We do not expect you to sanitise all of the queries since that would take too much time and would be lengthy. Sanitise all queries in the pages connected to the home page. This includes Items Page, Selling Page, Sell Page and the transactions. This issue has higher points awarded since it involves a higher number of pages. 

# Possible Way To Fix It
Use pattern matching/ text parsing specific to the context to sanitise the SQL queries. Another way is to use the sanitisation feature of [SQLAlchemy](https://www.sqlalchemy.org/)

# Resources
[SQLAlchemy Sanitisation](https://stackoverflow.com/questions/1997468/sanitizing-user-provided-sql-with-python)

# Bounty Points: 40 - 80 Depending on the number of queries sanitised and the amount of login/code required.

**Comment by shrutidewan** [comment]
can I work on this?

**Comment by anuragrao04** [comment]
go ahead

**Comment by anuragrao04** [comment]
the issue is open again

**Comment by MaNameEJeff** [comment]
Please can you assign me to this :)

**Comment by anuragrao04** [comment]
go ahead if you have time

**Comment by g-anupam** [comment]
can i be assigned this

**Comment by anuragrao04** [comment]
@g-anupam go ahead!

**Comment by AdiXgit** [comment]
can i be assigned

**Comment by akdino** [comment]
can i be assigned

**Comment by DedLad** [comment]
can i have?
